name: Mon premier workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VARIABLE_NAME: value

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: ./vendor/bin/phpunit
